sudo: false
language: node_js
services:
  - couchdb
node_js:
  - "stable"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage
branches:
  only:
  - master
